[package]
name = "game"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = { workspace = true }
egui = { workspace = true }
egui-macroquad = { workspace = true }

simulation = { workspace = true }
